name: 1m5-desktop
version: '0.6.5-SNAPSHOT'
summary: |
  Invisible Matrix Services - Uncensored Communciations
description: |
    A secure open-source decentralized peer-to-peer
    application platform with end-to-end encryption and
    anonymity as a base layer for creating easy to build
    and use secure decentralized peer-to-peer applications
    requiring no servers that can be used around the world
    by any person looking to protect their communications
    and personal data from unjust intrusion, interception,
    monitoring, and censorship.

confinement: devmode

parts:
    1m5-desktop:
    after: [desktop-glib-only]
    plugin: maven
    source: .
    build: |
      export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
      mvn release:perform
    install: |
      unzip DIST/1m5_bin-*.zip -d \
      $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - unzip
      - openjdk-11-jdk

apps:
    1m5-desktop:
    command: desktop-launch \
      $SNAP/1m5-0.6.5/1m5.sh
